### ISSUE TITLE
runhubot does not work4

### ISSUE THREAD

**Issue by k-okada** [k-okada/tools#11]
```
jenkins@jenkins:~/tools/travis-bot$ ./runhubot 
npm WARN prefer global pm2@0.14.7 should be installed with -g
[Fri Sep 25 2015 12:13:32 GMT+0900 (JST)] INFO Connecting...
[Fri Sep 25 2015 12:13:34 GMT+0900 (JST)] INFO Logged in as restart of JSK Robotics Lab, but not yet connected
[Fri Sep 25 2015 12:13:35 GMT+0900 (JST)] INFO Slack client now connected
[Fri Sep 25 2015 12:13:35 GMT+0900 (JST)] ERROR Unable to load /var/lib/jenkins/tools/travis-bot/scripts/github-issue-autoedit: Error: OAuth2 authentication requires a token or key & secret to be set
  at [object Object].authenticate (/var/lib/jenkins/tools/travis-bot/node_modules/github/index.js:428:23)
  at Object.<anonymous> (/var/lib/jenkins/tools/travis-bot/scripts/github-issue-autoedit.coffee:14:7, <js>:13:10)
  at Object.<anonymous> (/var/lib/jenkins/tools/travis-bot/scripts/github-issue-autoedit.coffee:7:1, <js>:69:4)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:182:19)
  at Module.load (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Robot.loadFile (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/src/robot.coffee:337:9, <js>:215:20)
  at Robot.load (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/src/robot.coffee:359:9, <js>:238:30)
  at SlackBot.loadScripts (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/bin/hubot:95:5, <js>:98:13)
  at SlackBot.emit (events.js:92:17)
  at SlackBot.open (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/src/slack.coffee:86:5, <js>:127:19)
  at Client.<anonymous> (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/src/slack.coffee:1:1, <js>:3:61)
  at Client.emit (events.js:92:17)
  at Client.onMessage (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/src/client.js:450:21)
  at WebSocket.<anonymous> (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/src/client.js:140:24)
  at WebSocket.emit (events.js:98:17)
  at Receiver.self._receiver.ontext (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:697:10)
  at Receiver.opcodes.1.finish (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:397:14)
  at Receiver.expectHandler (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:384:31)
  at Receiver.add (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:93:24)
  at CleartextStream.firstHandler (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:678:22)
  at CleartextStream.emit (events.js:95:17)
  at CleartextStream.<anonymous> (_stream_readable.js:765:14)
  at CleartextStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at _stream_readable.js:420:7
  at process._tickCallback (node.js:448:13)
```

**Comment by k-okada** [comment]
```
export HUBOT_GITHUB_TOKEN=$okada_TOKEN
```

としていたけど，これはtravsのtoken， githubのtokenが必要なのか．

**Comment by wkentaro** [comment]
すみません、そうです。
GItHubのTokenが必要です。

2015年9月25日金曜日、Kei Okadanotifications@github.comさんは書きました:

> export HUBOT_GITHUB_TOKEN=$okada_TOKEN
> 
> としていたけど，これはtravsのtoken， githubのtokenが必要なのか．
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-okada/tools/issues/11#issuecomment-143117024.

## 

和田 健太郎 / Kentaro Wada
http://wkentaro.com
