### ISSUE TITLE
runbotが死んでいる

### ISSUE THREAD

**Issue by k-okada** [k-okada/tools#18]
```
[Fri Oct 30 2015 11:20:57 GMT+0900 (JST)] ERROR TypeError: Cannot read property 'length' of undefined
  at /var/lib/jenkins/tools/travis-bot/scripts/travis-notification.coffee:44:9, <js>:37:36
  at Object.proto.sendError (/var/lib/jenkins/tools/travis-bot/node_modules/github/api/v3.0.0/index.js:32:13)
  at /var/lib/jenkins/tools/travis-bot/node_modules/github/api/v3.0.0/orgs.js:183:29
  at callCallback (/var/lib/jenkins/tools/travis-bot/node_modules/github/index.js:743:17)
  at IncomingMessage.<anonymous> (/var/lib/jenkins/tools/travis-bot/node_modules/github/index.js:793:25)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:448:13)

[Fri Oct 30 2015 11:27:39 GMT+0900 (JST)] ERROR TypeError: Cannot read property 'length' of undefined
  at /var/lib/jenkins/tools/travis-bot/scripts/travis-notification.coffee:44:9, <js>:37:36
  at Object.proto.sendError (/var/lib/jenkins/tools/travis-bot/node_modules/github/api/v3.0.0/index.js:32:13)
  at /var/lib/jenkins/tools/travis-bot/node_modules/github/api/v3.0.0/orgs.js:183:29
  at callCallback (/var/lib/jenkins/tools/travis-bot/node_modules/github/index.js:743:17)
  at IncomingMessage.<anonymous> (/var/lib/jenkins/tools/travis-bot/node_modules/github/index.js:793:25)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:448:13)

[Fri Oct 30 2015 11:32:30 GMT+0900 (JST)] ERROR TypeError: Cannot read property 'length' of undefined
  at /var/lib/jenkins/tools/travis-bot/scripts/travis-notification.coffee:44:9, <js>:37:36
  at Object.proto.sendError (/var/lib/jenkins/tools/travis-bot/node_modules/github/api/v3.0.0/index.js:32:13)
  at /var/lib/jenkins/tools/travis-bot/node_modules/github/api/v3.0.0/orgs.js:183:29
  at callCallback (/var/lib/jenkins/tools/travis-bot/node_modules/github/index.js:743:17)
  at IncomingMessage.<anonymous> (/var/lib/jenkins/tools/travis-bot/node_modules/github/index.js:793:25)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:448:13)

[Fri Oct 30 2015 11:38:33 GMT+0900 (JST)] ERROR TypeError: Cannot read property 'length' of undefined
  at /var/lib/jenkins/tools/travis-bot/scripts/travis-notification.coffee:44:9, <js>:37:36
  at Object.proto.sendError (/var/lib/jenkins/tools/travis-bot/node_modules/github/api/v3.0.0/index.js:32:13)
  at /var/lib/jenkins/tools/travis-bot/node_modules/github/api/v3.0.0/orgs.js:183:29
  at callCallback (/var/lib/jenkins/tools/travis-bot/node_modules/github/index.js:743:17)
  at IncomingMessage.<anonymous> (/var/lib/jenkins/tools/travis-bot/node_modules/github/index.js:793:25)
  at IncomingMessage.emit (events.js:117:20)
  at _stream_readable.js:944:16
  at process._tickCallback (node.js:448:13)

[Fri Oct 30 2015 11:51:48 GMT+0900 (JST)] ERROR Last pong is too old: 14.819
[Fri Oct 30 2015 11:51:48 GMT+0900 (JST)] INFO Reconnecting in 1000ms
[Fri Oct 30 2015 11:51:49 GMT+0900 (JST)] INFO Attempting reconnect
[Fri Oct 30 2015 11:51:49 GMT+0900 (JST)] INFO Connecting...
[Fri Oct 30 2015 11:51:51 GMT+0900 (JST)] INFO Logged in as restart of JSK Robotics Lab, but not yet connected
[Fri Oct 30 2015 11:51:51 GMT+0900 (JST)] INFO Slack client closed
```

**Comment by k-okada** [comment]
https://github.com/k-okada/tools/pull/17#issuecomment-152452290
で議論がある
