### ISSUE TITLE
runhubot does not work

### ISSUE THREAD

**Issue by k-okada** [k-okada/tools#6]
どうやって動作確認している？

```
$ ./runhubot
npm WARN prefer global pm2@0.14.7 should be installed with -g
[Thu Sep 24 2015 16:39:15 GMT+0900 (JST)] INFO Connecting...
[Thu Sep 24 2015 16:39:15 GMT+0900 (JST)] ERROR Error: listen EADDRINUSE
  at errnoException (net.js:905:11)
  at Server._listen2 (net.js:1043:14)
  at listen (net.js:1065:10)
  at net.js:1147:9
  at dns.js:72:18
  at process._tickCallback (node.js:448:13)

[Thu Sep 24 2015 16:39:17 GMT+0900 (JST)] INFO Logged in as restart of JSK Robotics Lab, but not yet connected
[Thu Sep 24 2015 16:39:18 GMT+0900 (JST)] INFO Slack client now connected
[Thu Sep 24 2015 16:39:18 GMT+0900 (JST)] ERROR Unable to load /var/lib/jenkins/tools/travis-bot/scripts/github-issue-autoedit: SyntaxError: unexpected TERMINATOR
  at Object.exports.throwSyntaxError (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/helpers.js:197:13)
  at Object.parser.yy.parseError (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:265:20)
  at Object.parse (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/parser.js:537:22)
  at exports.compile.compile (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:35:24)
  at Object.loadFile (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:176:14)
  at Module.load (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Robot.loadFile (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/src/robot.coffee:337:9, <js>:215:20)
  at Robot.load (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/src/robot.coffee:359:9, <js>:238:30)
  at SlackBot.loadScripts (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/bin/hubot:95:5, <js>:98:13)
  at SlackBot.emit (events.js:92:17)
  at SlackBot.open (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/src/slack.coffee:86:5, <js>:127:19)
  at Client.<anonymous> (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/src/slack.coffee:1:1, <js>:3:61)
  at Client.emit (events.js:92:17)
  at Client.onMessage (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/src/client.js:450:21)
  at WebSocket.<anonymous> (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/src/client.js:140:24)
  at WebSocket.emit (events.js:98:17)
  at Receiver.self._receiver.ontext (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:697:10)
  at Receiver.opcodes.1.finish (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:397:14)
  at Receiver.expectHandler (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:384:31)
  at Receiver.add (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:93:24)
  at CleartextStream.firstHandler (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:678:22)
  at CleartextStream.emit (events.js:95:17)
  at CleartextStream.<anonymous> (_stream_readable.js:765:14)
  at CleartextStream.emit (events.js:92:17)
  at emitReadable_ (_stream_readable.js:427:10)
  at _stream_readable.js:420:7
  at process._tickCallback (node.js:448:13)
```

**Comment by wkentaro** [comment]
github-issue-autoeditの方は、webhookを登録した後と考えていたので、エラーが出るようでしたら、リバートか消すかしてください。

まず自分のbot (wkentaro/lora)
で試してみることにします。

2015年9月24日木曜日、Kei Okadanotifications@github.comさんは書きました:

> どうやって動作確認している？
> 
> $ ./runhubot
> npm WARN prefer global pm2@0.14.7 should be installed with -g
> [Thu Sep 24 2015 16:39:15 GMT+0900 (JST)] INFO Connecting...
> [Thu Sep 24 2015 16:39:15 GMT+0900 (JST)] ERROR Error: listen EADDRINUSE
>   at errnoException (net.js:905:11)
>   at Server._listen2 (net.js:1043:14)
>   at listen (net.js:1065:10)
>   at net.js:1147:9
>   at dns.js:72:18
>   at process._tickCallback (node.js:448:13)
> 
> [Thu Sep 24 2015 16:39:17 GMT+0900 (JST)] INFO Logged in as restart of JSK Robotics Lab, but not yet connected
> [Thu Sep 24 2015 16:39:18 GMT+0900 (JST)] INFO Slack client now connected
> [Thu Sep 24 2015 16:39:18 GMT+0900 (JST)] ERROR Unable to load /var/lib/jenkins/tools/travis-bot/scripts/github-issue-autoedit: SyntaxError: unexpected TERMINATOR
>   at Object.exports.throwSyntaxError (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/helpers.js:197:13)
>   at Object.parser.yy.parseError (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:265:20)
>   at Object.parse (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/parser.js:537:22)
>   at exports.compile.compile (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:35:24)
>   at Object.loadFile (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:176:14)
>   at Module.load (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/coffee-script/lib/coffee-script/coffee-script.js:211:36)
>   at Function.Module._load (module.js:312:12)
>   at Module.require (module.js:364:17)
>   at require (module.js:380:17)
>   at Robot.loadFile (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/src/robot.coffee:337:9, <js>:215:20)
>   at Robot.load (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/src/robot.coffee:359:9, <js>:238:30)
>   at SlackBot.loadScripts (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/bin/hubot:95:5, <js>:98:13)
>   at SlackBot.emit (events.js:92:17)
>   at SlackBot.open (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/src/slack.coffee:86:5, <js>:127:19)
>   at Client.<anonymous> (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/src/slack.coffee:1:1, <js>:3:61)
>   at Client.emit (events.js:92:17)
>   at Client.onMessage (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/src/client.js:450:21)
>   at WebSocket.<anonymous> (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/src/client.js:140:24)
>   at WebSocket.emit (events.js:98:17)
>   at Receiver.self._receiver.ontext (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:697:10)
>   at Receiver.opcodes.1.finish (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:397:14)
>   at Receiver.expectHandler (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:384:31)
>   at Receiver.add (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/Receiver.js:93:24)
>   at CleartextStream.firstHandler (/var/lib/jenkins/tools/travis-bot/node_modules/hubot-slack/node_modules/slack-client/node_modules/ws/lib/WebSocket.js:678:22)
>   at CleartextStream.emit (events.js:95:17)
>   at CleartextStream.<anonymous> (_stream_readable.js:765:14)
>   at CleartextStream.emit (events.js:92:17)
>   at emitReadable_ (_stream_readable.js:427:10)
>   at _stream_readable.js:420:7
>   at process._tickCallback (node.js:448:13)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-okada/tools/issues/6.

## 

和田 健太郎 / Kentaro Wada
http://wkentaro.com

**Comment by wkentaro** [comment]
https://github.com/k-okada/tools/pull/8
で直しましたが，webhook指定URLの問題 #2 があります．
