### ISSUE TITLE
runbot does not work2

### ISSUE THREAD

**Issue by k-okada** [k-okada/tools#9]
```
[Fri Sep 25 2015 10:57:28 GMT+0900 (JST)] INFO Logged in as restart of JSK Robotics Lab, but not yet connected
[Fri Sep 25 2015 10:57:29 GMT+0900 (JST)] INFO Slack client now connected
[Fri Sep 25 2015 10:57:29 GMT+0900 (JST)] ERROR hubot-heroku-alive included, but missing HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set HUBOT_HEROKU_KEEPALIVE_URL=$(heroku apps:info -s  | grep web_url | cut -d= -f2)`
[Fri Sep 25 2015 10:57:29 GMT+0900 (JST)] INFO hubot-redis-brain: Using default redis on localhost:6379
[Fri Sep 25 2015 10:57:29 GMT+0900 (JST)] INFO hubot-redis-brain: Data for hubot brain retrieved from Redis
[Fri Sep 25 2015 10:57:32 GMT+0900 (JST)] ERROR TypeError: Cannot read property '1' of null
  at /var/lib/jenkins/tools/travis-bot/scripts/travis-notification.coffee:29:7, <js>:18:26
  at Listener.callback (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/src/robot.coffee:233:52, <js>:158:16)
  at executeListener (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/src/listener.coffee:65:11, <js>:53:19)
  at allDone (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/src/middleware.coffee:41:37, <js>:32:16)
  at /var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/async/lib/async.js:274:13
  at Object.async.eachSeries (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/async/lib/async.js:142:20)
  at Object.async.reduce (/var/lib/jenkins/tools/travis-bot/node_modules/hubot/node_modules/async/lib/async.js:268:15)
  at /var/lib/jenkins/tools/travis-bot/node_modules/hubot/src/middleware.coffee:46:7, <js>:35:22
  at process._tickCallback (node.js:448:13)
```

`HUBOT_HEROKU_KEEPALIVE_URL. `heroku config:set`
と言われるのは正しい？

**Comment by furushchev** [comment]
これは
https://github.com/k-okada/tools/blob/master/travis-bot/external-scripts.json#L4
でherokuにdeployする用のプラグインを有効にしているからだと思います。

**Comment by wkentaro** [comment]
@k-okada
その行は消して大丈夫です。

2015年9月25日金曜日、Furushchevnotifications@github.comさんは書きました:

> これは
> 
> https://github.com/k-okada/tools/blob/master/travis-bot/external-scripts.json#L4
> でherokuにdeployする用のプラグインを有効にしているからだと思います。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/k-okada/tools/issues/9#issuecomment-143121635.

## 

和田 健太郎 / Kentaro Wada
http://wkentaro.com
